version: '3'
services:
  mongo:
    network_mode: 'bridge'
    container_name: mongo
    image: mongo:4.1
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    network_mode: 'bridge'
    container_name: mongo_express
    image: mongo-express:latest
    restart: always
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
